repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3.6
    exclude: __openerp__.py|__manifest__.py|odoo/external-src/
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
    exclude: odoo/patches/|odoo/external-src/
  - id: end-of-file-fixer
    exclude: odoo/patches/|odoo/external-src/
  - id: check-yaml
    files: odoo/migration.yml|odoo/pending-merges.yaml
  - id: debug-statements
    language_version: python3.6
    exclude: odoo/external-src/
  - id: flake8
    name: flake8 except __init__.py
    args: [--exclude=__init__.py]
    exclude: odoo/external-src/
    language_version: python3.6
  - id: flake8
    name: flake8 only __init__.py
    args: [--ignore=F401]  # ignore imported unused in __init__.py
    files: __init__.py
    exclude: odoo/external-src/
    language_version: python3.6
- repo: https://github.com/asottile/pyupgrade
  rev: v1.12.0
  hooks:
  - id: pyupgrade
    exclude: odoo/external-src/
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    exclude: odoo/external-src/
