language: python

python:
  - "2.7"

env:
  - 
  - RUNTESTS=1 EXCLUDE=last_sale_price
  - RUNTESTS=1 INCLUDE=last_sale_price

cache:
  directories:
    - ${HOME}/.eggs-cache

virtualenv:
  system_site_packages: true

before_install:
  - echo -e "Host bazaar.launchpad.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host bazaar.camptocamp.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - mkdir ~/.bazaar
  - echo -e "[DEFAULT]\nlaunchpad_username = camptocamp-business-robot\n" > ~/.bazaar/bazaar.conf
  - echo -e "[Launchpad]\nhost = .launchpad.net\nuser = camptocamp-business-robot\n" > ~/.bazaar/authentication.conf
  - echo -e "[c2cbazaar]\nhost = bazaar.camptocamp.net\nuser = openerp\n" >> ~/.bazaar/authentication.conf
  - git config --global user.name "TravisCI"
  - git config --global user.email "travis@camptocamp.com"
  - pip install -q flake8 flake8-debugger flake8-print coverage
  - sudo apt-get -q -y install expect-dev # provides unbuffer utility
  - mkdir ${HOME}/.buildout
  - echo -e "[buildout]\neggs-directory = "${HOME}"/.eggs-cache\n" > ~/.buildout/default.cfg

install:
  - echo -e "[buildout]\nextends = profiles/travis.cfg\n" > ${TRAVIS_BUILD_DIR}/buildout.cfg
  - ${TRAVIS_BUILD_DIR}/bootstrap.sh
  - ${TRAVIS_BUILD_DIR}/bin/buildout

before_script:
  - export DB_NAME=$(grep db_name ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export DB_USER=$(grep db_user ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export DB_PASS=$(grep db_password ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)

script:
  - if [ -z "$RUNTESTS" ] ; then flake8 ${TRAVIS_BUILD_DIR}/specific-parts/specific-addons --exclude=__init__.py; fi
  - if [ -n "$RUNTESTS" ] ; then ./test_server; fi
