sudo: false

addons:
  apt:
    packages:
    - libcups2-dev
    - expect-dev
    - wget

language: python

python:
  - "2.7"

# specific_fct and stockit_synchro fail because they install product_multi_ean
# and point_of_sale and point_of_sale can no longer create products with
# product_multi_ean...
# Thus they are not tested until a solution is found
env:
  - RUNTESTS=1 EXCLUDE=last_sale_price,specific_fct,stockit_synchro
  - RUNTESTS=1 INCLUDE=last_sale_price

virtualenv:
  system_site_packages: true

before_install:
  - pip install invoke
  - git config --global user.name "TravisCI"
  - git config --global user.email "travis@camptocamp.com"
  - pip install -q flake8 flake8-debugger flake8-print coverage

install:
  - git submodule update --init
  - invoke env.init -s -r profiles/travis.cfg
  - bin/buildout -N

before_script:
  - export DB_NAME=$(grep db_name ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export DB_USER=$(grep db_user ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)
  - export DB_PASS=$(grep db_password ${TRAVIS_BUILD_DIR}/etc/openerp.cfg | cut -d ' ' -f 3)

script:
  - if [ -z "$RUNTESTS" ] ; then flake8 ${TRAVIS_BUILD_DIR}/specific-parts/specific-addons --exclude=__init__.py; fi
  - if [ -n "$RUNTESTS" ] ; then ${TRAVIS_BUILD_DIR}/sandbox/bin/python ${TRAVIS_BUILD_DIR}/test_server; fi
